### ISSUE TITLE
Validate configured ip addresses are valid

### ISSUE THREAD

**Issue by felbinger** [secshellnet/ansible-vyos-validator#1]
Verify that the configured ipv4 / ipv6 addresses in `hosts.yaml` are valid.
You can do that by checking every leaf of the tree in `all.vars.v4` / `all.vars.v6`.
Only if the key, contains `_net` or `_vpn` a netmask (`/n`) should be given.

Example:
```yaml
# hosts.yaml
all:
  vars:
    v4:
      site_net: "192.168.0.0/17"
      site_vpn: "192.168.200.0/24"
      site:
        device1: "192.168.100.1"
        device_b: "192.168.100.2"
        deviceC: "192.168.25.3"

    v6:
      site_net: "fd00::/62"
      site_vpn: "fd00:0:0:4::/63"
      site_vpn2: "fd00:0:0:6::/64"
      site:
        device1:
          ipv6A: "fd00::1234:1234:1245"
          ipv6_b: "fd00::1234:1234:1245"
        device_b:
          host: "fd00::5"
        deviceC:
          host: "fd01::"
```
You should not check if the `v4` and `v6` have the same hosts.
Devices can not contain an ipv6 address directly, we need one specific address with a key in it.
