### ISSUE TITLE
Validate configured ip address variables are valid

### ISSUE THREAD

**Issue by felbinger** [secshellnet/ansible-vyos-validator#2]
The ip addresses in the `host.yaml` file (see #1) are being used within the playbooks as ip addresses (single source of truth!).

Create a validator to check if the configured addresses are valid yaml path in `hosts.yaml`.

Most of the time these variables are used behind the `address` key (either in `source` or `destination` for firewall rules, or when used with nat maybe behind `translation`).

```yaml
---
- name: Configure destination nat
  vyos.vyos.vyos_config:
    save: true
    match: none
    lines:
      - "set nat destination rule 100 destination port 8980"
      - "set nat destination rule 100 inbound-interface eth1"
      - "set nat destination rule 100 protocol tcp"
      - "set nat destination rule 100 translation address {{ v4.site.service }}"    # <------ HERE
      - "set nat destination rule 100 translation port 80"


- name: "Configure xxxx firewall ruleset (ipv4)"
  vyos.vyos.vyos_firewall_rules:
    state: replaced
    config:
      - afi: ipv4
        rule_sets:
          - name: xxxx
            default_action: drop
            enable_default_log: true
            rules:
              - number: 100
                action: accept
                destination:
                  address: "{{ v4.site.service + '/32' }}"                                  # <------ HERE
                  port: 80
                protocol: tcp
```

It would also be nice, if you could verify that every address line, which has an address without the `_net` / `_vpn` and belongs to `vyos.vyos.vyos_firewall_rules` has a netmask (`/n`) appended to it. 
This is not required by vyos from a technical perspective, but improves the ability to filter the logs.

Be aware that this does not work for things like nat, so ignore it for the whole action `vyos.vyos.vyos_config`!

Basicly the same for ipv6:
```yaml
---
- name: "Configure xxx firewall ruleset (ipv6)"
  vyos.vyos.vyos_firewall_rules:
    state: replaced
    config:
      - afi: ipv6
        rule_sets:
          - name: xxxxxx-6
            default_action: drop
            rules:
              - number: 100
                action: accept
                description: wpm.general.pve3.secshell.net
                destination:
                  address: "{{ v6.site.device.ipaddr + '/128' }}"
                  port: 443
                protocol: tcp

```
