### ISSUE TITLE
Validate configuration for action vyos_logging_global

### ISSUE THREAD

**Issue by felbinger** [secshellnet/ansible-vyos-validator#5]
https://docs.ansible.com/ansible/latest/collections/vyos/vyos/vyos_logging_global_module.html
```yaml
---
- name: "Configuration syslog"
  vyos.vyos.vyos_logging_global:
    state: merged
    config:
      hosts:
        - hostname: graylog.domain.de
          port: 1514
          facilities:
            - facility: all
              severity: debug
              protocol: udp
```
